apiVersion: apps/v1
kind: Deployment
metadata:
  name: seconddeploy
  labels:
    name: seconddeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
